#!/bin/sh

# pkg-config
PKG_CONFIG_SRC="https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz"

# Source files for qemu
FFI_SRC="https://sourceware.org/ftp/libffi/libffi-3.3.tar.gz"
ICONV_SRC="https://ftp.gnu.org/gnu/libiconv/libiconv-1.16.tar.gz"
GETTEXT_SRC="https://ftp.gnu.org/gnu/gettext/gettext-0.21.tar.gz"
PNG_SRC="https://ftp.osuosl.org/pub/blfs/conglomeration/libpng/libpng-1.6.37.tar.xz"
JPEG_TURBO_SRC="https://ftp.osuosl.org/pub/blfs/conglomeration/libjpeg-turbo/libjpeg-turbo-1.5.3.tar.gz"
GLIB_SRC="https://download.gnome.org/sources/glib/2.70/glib-2.70.2.tar.xz"
GPG_ERROR_SRC="https://www.gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-1.43.tar.gz"
GCRYPT_SRC="https://www.gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.9.4.tar.bz2"
PIXMAN_SRC="https://www.cairographics.org/releases/pixman-0.40.0.tar.gz"
OPENSSL_SRC="https://www.openssl.org/source/old/1.1.1/openssl-1.1.1b.tar.gz"
OPUS_SRC="https://archive.mozilla.org/pub/opus/opus-1.3.tar.gz"
XINERAMA="https://www.x.org/archive//individual/lib/libXinerama-1.1.4.tar.gz"
XFIXES="https://www.x.org/archive//individual/lib/libXfixes-6.0.0.tar.bz2"
XRANDR="https://www.x.org/archive//individual/lib/libXrandr-1.5.2.tar.bz2"
XTRANS="https://www.x.org/archive//individual/lib/xtrans-1.4.0.tar.gz"
X11="https://www.x.org/archive//individual/lib/libX11-1.7.3.1.tar.gz"
SPICE_VGAGENT="https://www.spice-space.org/download/releases/spice-vdagent-0.21.0.tar.bz2"
# It seems that spice-gtk 0.36 is not compatible with spice-protocol 0.14
SPICE_PROTOCOL_SRC="https://www.spice-space.org/download/releases/spice-protocol-0.12.15.tar.bz2"
# spice-0.15 requested 'spice-protocol >= 0.14.3' but version of spice-protocol is 0.12.15
SPICE_SERVER_SRC="https://www.spice-space.org/download/releases/spice-server/spice-0.14.1.tar.bz2"
USB_SRC="https://github.com/libusb/libusb/releases/download/v1.0.24/libusb-1.0.24.tar.bz2"
USBREDIR_SRC="https://www.spice-space.org/download/usbredir/usbredir-0.12.0.tar.xz"
QEMU_SRC="https://github.com/utmapp/qemu/releases/download/v6.1.0-utm/qemu-6.1.0-utm.tar.bz2"

# Source files for spice-client
JSON_GLIB_SRC="https://download.gnome.org/sources/json-glib/1.6/json-glib-1.6.6.tar.xz"
GST_SRC="https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.19.3.tar.xz"
GST_BASE_SRC="https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.19.3.tar.xz"
GST_GOOD_SRC="https://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-1.19.3.tar.xz"
XML2_SRC="http://xmlsoft.org/sources/libxml2-2.9.12.tar.gz"
NGHTTP2="https://github.com/nghttp2/nghttp2/releases/download/v1.46.0/nghttp2-1.46.0.tar.bz2"
SQLITE3="https://www.sqlite.org/2021/sqlite-autoconf-3370000.tar.gz"
LIBPSL="https://github.com/rockdaboot/libpsl/releases/download/0.21.1/libpsl-0.21.1.tar.gz"
POLKIT="https://gitlab.freedesktop.org/polkit/polkit/-/archive/0.120/polkit-0.120.tar.bz2"
SYSPROF="https://gitlab.gnome.org/GNOME/sysprof/-/archive/3.42.1/sysprof-3.42.1.tar.bz2"
EXPAT="https://github.com/libexpat/libexpat/releases/download/R_2_4_1/expat-2.4.1.tar.bz2"
GRAPHENE="https://github.com/ebassi/graphene/releases/download/1.10.6/graphene-1.10.6.tar.xz"
GTK="https://gitlab.gnome.org/GNOME/gtk/-/archive/4.5.1/gtk-4.5.1.tar.bz2"
ATK="https://gitlab.gnome.org/GNOME/atk/-/archive/ATK_2_36_0/atk-ATK_2_36_0.tar.bz2"
PANGO="https://gitlab.gnome.org/GNOME/pango/-/archive/1.50.2/pango-1.50.2.tar.bz2"
FRIBIDI="https://github.com/fribidi/fribidi/releases/download/v1.0.11/fribidi-1.0.11.tar.xz"
CAIRO="https://cairographics.org/snapshots/cairo-1.17.4.tar.xz"
PIXBUF="https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/archive/2.42.6/gdk-pixbuf-2.42.6.tar.bz2"
INTROSPECTION="https://gitlab.gnome.org/GNOME/gobject-introspection/-/archive/1.70.0/gobject-introspection-1.70.0.tar.bz2"
GTK3="https://download.gnome.org/sources/gtk+/3.24/gtk%2B-3.24.31.tar.xz"
# 2.65 needs for phodav-2.2
SOUP_SRC="https://ftp.gnome.org/pub/GNOME/sources/libsoup/2.65/libsoup-2.65.1.tar.xz"
# only 2.2 was successfully built
PHODAV_SRC="https://download.gnome.org/sources/phodav/2.2/phodav-2.2.tar.xz"
# 0.39 - subprojects/spice-common/meson.build:137:8: ERROR: Problem encountered: Python module six not found
SPICE_CLIENT_SRC="https://www.spice-space.org/download/gtk/spice-gtk-0.36.tar.bz2"

# Source files for GPU acceleration
DEPOT_TOOLS_REPO="https://chromium.googlesource.com/chromium/tools/depot_tools.git"
DEPOT_TOOLS_COMMIT="1cabb17575917b73ec2e270d4187656c20b1ab0c"
ANGLE_REPO="https://github.com/utmapp/angle.git"
ANGLE_COMMIT="c89da01e8e4d7c17ca00a2e3eafe02f4515c3960"
EPOXY_REPO="https://github.com/utmapp/libepoxy.git"
EPOXY_COMMIT="266d2290a437c655f7419e85af06bfbb73a720c4"
VIRGLRENDERER_REPO="https://github.com/utmapp/virglrenderer.git"
VIRGLRENDERER_COMMIT="e07cc2b5e320aab55b1295b66c83a59e0897a83e"