name: Windows

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-win" 

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [x86_64]
        platform: [windows]
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Cat
        shell: pwsh 
        run: |
          dir C:\msys64\mingw64\include\
          type "C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\shared\afunix.h"
          type "C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\shared\afunix.h"
          type "C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\afunix.h"
          type "C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\afunix.h"


      - name: Branch name
        id: branch_name
        shell: bash
        run: |
          echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            git

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install libs
        run: |
          pacman -Suy --noconfirm
          pacman -Sy --noconfirm mingw-w64-x86_64-gcc python
          pacman -Sy --noconfirm mingw-w64-x86_64-toolchain
          pacman -Sy --noconfirm mingw-w64-x86_64-glib2 mingw-w64-x86_64-gtk3 mingw-w64-x86_64-SDL2
          pacman -Sy --noconfirm ninja
          pacman -Sy --noconfirm mingw-w64-x86_64-diffutils

      - name: Build
        run: |
          pwd
          ls -l
          BUILD_PATH=$HOME/QEMU-bin
          mkdir bin
          git clone git://git.qemu-project.org/qemu.git
          cd qemu
          git reset --hard 44f28df24767cf9dca1ddc9b23157737c4cbb645
          patch util/qemu-sockets.c ../qemu-win/util/qemu-sockets.c.patch
          patch chardev/char-socket.c ../qemu-win/chardev/char-socket.c.patch
          patch tests/unit/test-util-sockets.c ../qemu-win/tests/unit/test-util-sockets.c.patch
          git submodule init
          git submodule update --recursive
          ./configure --prefix=$BUILD_PATH --target-list=x86_64-softmmu --disable-capstone
          echo 'make'
          make
          echo 'make ok'
          make install
          echo 'make install ok'
          cd ../
          cp /mingw64/bin/*.dll bin/
          mv $BUILD_PATH/share .
          mv $BUILD_PATH/*.exe bin/
      
      - name: Compress
        run: |
          tar -czvf "qemu-${{ steps.branch_name.outputs.TAG }}-windows-x86_64.tgz" bin share
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.tgz
          prerelease: true
