name: build-alpine-qemu-ga

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-alpine"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
        platform: [linux]
    steps:
      - name: Branch name
        id: branch_name
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: setup-qemu-action
        uses: docker/setup-qemu-action@v1

      - name: Build in docker
        run: |
          docker run --entrypoint /bin/sh --name qemu --platform linux/${{ matrix.arch }} alpine -c "pwd && \
          cd /root/ && \ 
          mkdir $HOME/QEMU-bin && \
          apk update && \
          apk add git python3 make ninja gcc g++ musl-dev pkgconfig glib-dev pixman-dev perl && \
          BUILD_PATH=$HOME/QEMU-bin && \
          mkdir bin && \
          git clone git://git.qemu-project.org/qemu.git && \
          cd qemu && \
          git reset --hard 44f28df24767cf9dca1ddc9b23157737c4cbb645 && \
          git submodule init && \
          git submodule update --recursive && \
          ./configure --prefix=$BUILD_PATH --target-list=x86_64-softmmu --disable-capstone && \
          cd build && \
          ninja"

          sudo docker cp qemu:/root/qemu/build/qga/qemu-ga .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            qemu-ga
          prerelease: true