name: build-alpine-qemu-ga

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-alpine"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
        platform: [linux]
    steps:
      - name: Branch name
        id: branch_name
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: setup-qemu-action
        uses: docker/setup-qemu-action@v1

      - name: Build in docker
        run: |
          docker run --entrypoint /bin/sh --name qemu --platform linux/${{ matrix.arch }} alpine -c "pwd && \
          cd /root/ && \ 
          apk update && \
          apk add git && \
          BUILD_PATH=$HOME/QEMU-bin && \
          mkdir bin && \
          git clone git://git.qemu-project.org/qemu.git && \
          cd qemu && \
          git reset --hard 44f28df24767cf9dca1ddc9b23157737c4cbb645 && \
          git submodule init && \
          git submodule update --recursive && \
          ./configure --enable-whpx --prefix=$BUILD_PATH --target-list=x86_64-softmmu --disable-capstone CFLAGS="-I/usr/include/" && \
          echo 'make' && \
          make && \
          echo 'make ok' && \
          make install && \
          cp /usr/bin/qemu-ga bin/ && \
          tar -czvf qemu-${{ steps.branch_name.outputs.SOURCE_TAG }}-${{ matrix.platform }}-${{ matrix.arch }}.tgz bin"

          sudo docker cp qemu:/root/qemu-${{ steps.branch_name.outputs.SOURCE_TAG }}-${{ matrix.platform }}-${{ matrix.arch }}.tgz .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.tgz
          prerelease: true