name: Windows

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-win" 

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86_64]
        platform: [windows]
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            git

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install 001
        if: false
        run: |
          pacman -Syu
          pacman -Su
          pacman -S mingw-w64-x86_64-toolchain --noconfirm
          pacman -S python --noconfirm
          pacman -S ninja --noconfirm
          pacman -S mingw-w64-x86_64-glib2 --noconfirm
          pacman -S mingw-w64-x86_64-gtk3 --noconfirm
          pacman -S mingw-w64-x86_64-SDL2 --noconfirm
          git clone git://git.qemu-project.org/qemu.git --branch stable-6.1 --single-branch
          # wget https://github.com/qemu/qemu/archive/refs/tags/v6.2.0.tar.gz
          # tar -xzf v6.2.0.tar.gz
          cd qemu
          git submodule update --init ui/keycodemapdb
          git submodule update --init capstone
          git submodule update --init dtc
          ./configure --enable-gtk --enable-sdl --target-list=x86_64-softmmu --disable-werror --disable-stack-protector --disable-capstone
          make
          qemu/x86_64-softmmu ./qemu-system-x86_64 -L ./../pc-bios

      - name: Install 002
        run: |
          pacman -Suy --noconfirm
          pacman -Sy --noconfirm mingw-w64-x86_64-gcc python
          pacman -Sy --noconfirm mingw-w64-x86_64-toolchain
          pacman -Sy --noconfirm mingw-w64-x86_64-glib2 mingw-w64-x86_64-gtk3 mingw-w64-x86_64-SDL2
          pacman -Sy --noconfirm ninja
          pacman -Sy --noconfirm mingw-w64-x86_64-diffutils
          git clone git://git.qemu-project.org/qemu.git
          cd qemu
          git submodule init
          git submodule update --recursive
          ./configure --target-list=x86_64-softmmu --disable-capstone --disable-werror --disable-stack-protector 
          echo 'make'
          make
          echo 'make ok'
