name: Windows

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-win-cygwin" 

jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe --login -o igncr '{0}'
    strategy:
      matrix:
        arch: [x86_64]
        platform: [windows]
    steps:
      - name: Branch name
        id: branch_name
        shell: bash
        run: |
          echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - name: Msgmerge fix
        shell: pwsh 
        run: |
          Remove-Item "C:\Program Files\Git\usr\bin\msgmerge.exe"

      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: wget

      - name: Install apt-cyg 
        run: |
          wget rawgit.com/transcode-open/apt-cyg/master/apt-cyg -O apt-cyg
          install apt-cyg /bin

      - name: Install libs
        run: |
          apt-cyg install gcc-core flexdll binutils cmake gcc-g++ automake autoconf libtool python flex bison coreutils libiconv libiconv-devel gettext po4a ncurses ninja genisoimage byacc libncurses-devel lynx gperf gettext-devel libreadline-devel  findutils-debuginfo wget libxml2-devel file-devel libtirpc-devel libjansson-devel pcre2 libpcre2-devel
      
      - name: Install glib2
        if: false
        run: |
          git clone https://github.com/GNOME/glib.git
          cd glib
          git reset --hard 4bd23d1b2676d7b60f6e9ef1013323e90bb0aacf
          meson _build                            
          ninja -C _build        
          ninja -C _build install     

      - name: Build
        run: |
          BUILD_PATH=$HOME/QEMU-bin
          mkdir $HOME/QEMU-bin
          mkdir bin
          git clone git://git.qemu-project.org/qemu.git
          cd qemu
          git reset --hard 44f28df24767cf9dca1ddc9b23157737c4cbb645
          git submodule init
          git submodule update --recursive
          ./configure --prefix=$BUILD_PATH --target-list=x86_64-softmmu --disable-capstone
          echo 'make'
          make
          echo 'make ok'
          make install
          echo 'make install ok'
          cd ../
          cp /bin/*.dll bin/
          mv $BUILD_PATH/share .
          mv $BUILD_PATH/*.exe bin/
      
      - name: Compress
        run: |
          tar -czvf "qemu-${{ steps.branch_name.outputs.TAG }}-windows-cygwin-x86_64.tgz" bin share
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.tgz
          prerelease: true
