name: Windows

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-win"

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86_64]
        platform: [windows]
    steps:
      - name: Branch name
        id: branch_name
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          mingw64.exe
