name: Macos gpu

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-gpu"

jobs:
  build:
    name: Build Qemu macos
    runs-on: macos-11
    strategy:
      matrix:
        arch: [arm64]
        platform: [macos]
        building-flags: [sdl, cocoa]
    steps:
      - name: Branch name
        id: branch_name
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Xcode
        shell: bash
        run: sudo xcode-select -switch /Applications/Xcode_13.2.1.app
      - name: Cache Sysroot
        id: cache-sysroot
        uses: actions/cache@v2
        with:
          path: sysroot-${{ matrix.platform }}-${{ matrix.arch }}
          key: ${{ matrix.platform }}-${{ matrix.arch }}-${{ hashFiles('scripts/build_dependencies.sh') }}-${{ hashFiles('patches/**') }}
      - name: Setup Path
        shell: bash
        run: |
          echo "/usr/local/opt/gettext/bin" >> $GITHUB_PATH
          echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH
      
      - name: Build Sysroot
        if: steps.cache-sysroot.outputs.cache-hit != 'true'
        run: |
          brew uninstall cmake
          brew install bison pkg-config nasm make meson glib
          rm -f /usr/local/lib/pkgconfig/*.pc
          ./scripts/build_dependencies.sh -p ${{ matrix.platform }} -a ${{ matrix.arch }} -f ${{ matrix.building-flags }}
      
      - name: Compress Sysroot
        if: steps.cache-sysroot.outputs.cache-hit != 'true' || github.event_name == 'release' || github.event.inputs.test_release == 'true'
        run: |
          cd sysroot-macOS-${{ matrix.arch }} && \
          tar -czvf qemu-${{ steps.branch_name.outputs.TAG }}-${{ matrix.building-flags }}-${{ matrix.platform }}-${{ matrix.arch }}.tgz ./ && \
          mv *.tgz ../
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.tgz
          prerelease: true