name: Macos gpu

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-gpu-cocoa"
      - "[0-9]+.[0-9]+.[0-9]+-gpu-sdl"

jobs:
  build:
    name: Build Qemu macos
    runs-on: macos-11
    strategy:
      matrix:
        arch: [arm64, x86_64]
        platform: [macos]
    steps:
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
          echo ::set-output name=QEMU_FLAG::$(echo ${GITHUB_REF#refs/tags/} | cut -d - -f 3)

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Xcode
        shell: bash
        run: sudo xcode-select -switch /Applications/Xcode_13.2.1.app
      - name: Cache Sysroot
        id: cache-sysroot
        uses: actions/cache@v2
        with:
          path: sysroot-${{ matrix.platform }}-${{ matrix.arch }}
          key: ${{ matrix.platform }}-${{ matrix.arch }}-${{ hashFiles('scripts/build_dependencies.sh') }}-${{ hashFiles('patches/**') }}
      - name: Setup Path
        shell: bash
        run: |
          echo "/usr/local/opt/gettext/bin" >> $GITHUB_PATH
          echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH
      
      - name: Build Sysroot
        if: steps.cache-sysroot.outputs.cache-hit != 'true'
        run: |
          echo "QEMU_FLAG: ${{ steps.branch_name.outputs.QEMU_FLAG }}"
          brew uninstall cmake
          brew install bison pkg-config nasm make meson glib
          rm -f /usr/local/lib/pkgconfig/*.pc
          ./scripts/build_dependencies.sh -p ${{ matrix.platform }} -a ${{ matrix.arch }} -f ${{ steps.branch_name.outputs.QEMU_FLAG }}
      
      - name: Compress Sysroot
        run: |
          cd sysroot-macOS-${{ matrix.arch }} && \
          tar -czvf qemu-${{ steps.branch_name.outputs.TAG }}-${{ matrix.platform }}-${{ matrix.arch }}.tgz ./ && \
          mv *.tgz ../

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.tgz
          prerelease: true