name: Windows

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-win" 

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86_64]
        platform: [windows]
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            git

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install
        run: |
          pacman -Syu
          pacman -Su
          echo 'installing base-devel'
          pacman -S base-devel --noconfirm
          pacman -S mingw-w64-x86_64-winstorecompat-git --noconfirm
          echo 'installing mingw-w64-x86_64-toolchain'
          yes J | pacman -S mingw-w64-x86_64-toolchain --noconfirm
          echo 'installing git'
          pacman -S git --noconfirm
          echo 'installing python'
          pacman -S python --noconfirm
          pacman -S mingw-w64-x86_64-glib2 --noconfirm
          pacman -S mingw-w64-x86_64-gtk3 --noconfirm
          pacman -S mingw-w64-x86_64-SDL2 --noconfirm
          git clone git://git.qemu-project.org/qemu.git
          cd qemu
          git submodule update --init ui/keycodemapdb
          git submodule update --init capstone
          git submodule update --init dtc
          ./configure --enable-gtk --enable-sdl --target-list=x86_64-softmmu --disable-werror --disable-stack-protector --disable-capstone
          make
          qemu/x86_64-softmmu ./qemu-system-x86_64 -L ./../pc-bios