name: Windows

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-windows" 

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86_64]
        platform: [windows]
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Branch name
        id: branch_name
        shell: bash
        run: |
          echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            git

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        run: |
          ls -lt /mingw64/bin/
          BUILD_PATH=$HOME/QEMU-bin
          mkdir bin
          mkdir libs
          pacman -Suy --noconfirm
          pacman -Sy --noconfirm mingw-w64-x86_64-gcc python
          pacman -Sy --noconfirm mingw-w64-x86_64-toolchain
          pacman -Sy --noconfirm mingw-w64-x86_64-glib2 mingw-w64-x86_64-gtk3 mingw-w64-x86_64-SDL2
          pacman -Sy --noconfirm ninja
          pacman -Sy --noconfirm mingw-w64-x86_64-diffutils
          git clone git://git.qemu-project.org/qemu.git
          cd qemu
          git reset --hard 44f28df24767cf9dca1ddc9b23157737c4cbb645
          git submodule init
          git submodule update --recursive
          ./configure --prefix=$BUILD_PATH --target-list=x86_64-softmmu --disable-capstone
          echo 'make'
          make
          echo 'make ok'
          make install
          echo 'make install ok'
          cd ../
          cp /mingw64/bin/*.dll libs/
          mv $BUILD_PATH/share .
          mv $BUILD_PATH/*.exe bin/
      
      - name: Compress
        run: |
          tar -czvf "qemu-${{ steps.branch_name.outputs.TAG }}-windows-x86_64.tgz" libs bin share
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.tgz
          prerelease: true
