name: Publish

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build-linux-dnf:
    if false:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        id: branch_name
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Install dependencies
        run: |
          echo ${{ steps.branch_name.outputs.SOURCE_TAG }}