name: Macos

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-test-mac-sign"

jobs:
  build-macos-ports:
    name: Build0
    runs-on: self-hosted
    steps:
      - name: Import signing certificate into keychain
        if: false
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
          p12-password: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}

      - name: Install dependencies
        run: |
          rm -rf x.cpp
          echo "#include <iostream>" >> x.cpp
          echo "int main() {" >> x.cpp
          echo "std::cout << \"Hello World!\";" >> x.cpp
          echo "return 0;}" >> x.cpp
          g++ x.cpp -o x
          chmod +x x

      - name: Notarize app
        run: npx notarize-cli --file "x" --bundle-id "app.kymano"
        env:
          NOTARIZE_USERNAME: ${{ secrets.SIGNING_USERNAME }}
          NOTARIZE_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}