name: Publish

on:
  push:
    tags:
      - "*.*.*-cocoa"
      - "*.*.*-gtk3"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/} && \
          echo ${GITHUB_REF}

      - name: Install dependencies
        run: |
          echo ${{ steps.branch_name.outputs.SOURCE_TAG }}