name: Macos

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-test-mac-sign"

jobs:
  build-macos-ports:
    name: Build0
    runs-on: macos-11
    steps:
      - name: Install dependencies
        run: |
          echo "#include <iostream>\n" >> x.cpp
          echo "int main() {\n" >> x.cpp
          echo "std::cout << \"Hello World!\";\n" >> x.cpp
          echo "return 0;\n" >> x.cpp
          echo "}\n"
          g++ x.cpp -o x
          chmod +x x
          ./x
