name: Publish

on:
  push:
    tags:
      - "*.*.*-cocoa"
      - "*.*.*-gtk3"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/} && \
          echo ::set-output name=SOURCE_TAG_OPTION::$(echo $GITHUB_REF | cut -d - -f 2) && \
          echo ${GITHUB_REF#refs/tags/} && \
          if [[ `echo ${GITHUB_REF#refs/tags/} | cut -d - -f 2` == 'cocoa' ]]; then echo "ok"; fi && \
          echo ${GITHUB_REF}

      - name: test 1
        run: |
          echo ${{ steps.branch_name.outputs.SOURCE_TAG }} && \
          echo ${{ steps.branch_name.outputs.SOURCE_TAG_OPTION }}
