name: Publish

on:
  push:
    tags:
      - "*.*.*-cocoa"
      - "*.*.*-gtk3"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/} && \
          case `echo ${GITHUB_REF#refs/tags/} | cut -d - -f 2` in 'cocoa') echo ::set-output name=VARIANT::$(echo '+cocoa');; 'gtk3') echo ::set-output name=VARIANT::$(echo '+gtk3');; esac

      - name: test 1
        run: |
          echo ${{ steps.branch_name.outputs.SOURCE_TAG }} && \
          echo ${{ steps.branch_name.outputs.VARIANT }}
